project:
  type: website
  output-dir: docs

book:
  title: "remote_sensing"
  author: "Atsumi Hirose"
  date: "01/02/2023"
  chapters:
    - index.qmd
    - week1.qmd
    - week2.qmd
    - week3.qmd
    - week4.qmd
    - week5.qmd
    - week6.qmd
    - week7.qmd
    - week8.qmd
    - references.qmd

bibliography: references.bib
website: 
  sidebar: 
    style: docked
    search: true
    contents: 
      - section: "Contents"
        contents: 
        - index.qmd
        - week1.qmd
        - week2.qmd
        - week3.qmd
        - week4.qmd
        - week5.qmd
        - week6.qmd
        - week7.qmd
        - week8.qmd
        - references.qmd
     
        
        
format:
  html:
    theme: cosmo
    toc: true
  pdf:
    documentclass: scrreprt

editor: visual

