project:
  type: website
  output-dir: docs

book:
  title: "remote_sensing"
  author: "Atsumi Hirose"
  date: "01/02/2023"
  chapters:
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib
website: 
  sidebar: 
    style: docked
    search: true
    contents: 
      - section: "Contents"
        contents: 
        - intro.qmd
        - summary.qmd
        - references.qmd
     
        
        
format:
  html:
    theme: cosmo
    toc: true
  pdf:
    documentclass: scrreprt

editor: visual

