# Introduction

This is a learning diary of Atsumi Hirose

I am looking forward to learning remote sensing on this module!

A bit of my backgruon as a way of introduction. I have (doctoral and postdoctoral) training in epidemiology of maternal and newborn health. I also have a master degree in Demography. While I was a student more than 10 years ago, I was interested in how gender roles affect women's decision to seek (delivery) care, mainly in South Asia (such as India, Pakistan, Afghanistan and so on).

Since then I have moved on (a lot). More recently, my research interests expanded to include spatial health inequalities particularly spatial factors that affect maternal and newborn health in resource-limited countries in Asia and Sub-Saharan Africa. I have become increasingly interested in measuring environmental factors and including them in research investigation. For example, how where pregnant women live (urban slums) or physical distances between home and healthcare services contribute to health and pregnancy outcome.

Traditional health survey data do not provide sufficient information with good coverage to understand the environments where women live in. In order to pursue my interest in spatial health inequalities, I have become interested to using Earth Observation data, thus, I am doing a master degree again.

Anyway, I am looking forward to learning how to manipulate remotely sensed data including Google Earth Engine later in the term.
