---
title: "Week 5"
author: "Atsumi Hirose"
editor: visual
---

# Summary

This week, we looked at Google Earth Engine (GEE).

What I understood is that GEE has got many images (including Landsat, Sentinel, MODIS, ASTER, USDA NAIP) and other data (such as Landcover, weather, precipitation and atmosphere and Population data) [@gorelick2017] that can be accessed on GEE and it is very easy to download data. Often, this is done by just a click. Another key feature of GEE is how fast it can process.

So that's all great. However, obviously, you will need to know javascript to take advantage of all that's offered in GEE. (So it is not that easy to use after all! ) GEE also provide Python API.

To note, Scale parameter

-   GEE aggregates the values based on your analysis.

Some analysis tools introduced this week is "Reducer".

Reducer types:

-   to get zonal statistics, use the reduceRegion method of the image class. The output is a dictionary containing the statistics (specified in the function) for each spectoral band for the entire study area. See a code example [here](https://code.earthengine.google.com/6a141faca9dd3cbe671de705890d83ea).

-   to get statistics of multiple regions, use the reduceRegions method of the image class. The output is the input features (like polygon) with reducer-applied values.

-   to get statistics by neighbourhood, use reduceNeighborhood method

-   Linear regressions are also considered 'reducer' in GEE

# Application

I explored what work has been done using GEE for global health research.

1.  For the implementation of a Malaria warning system which predicts future malaria risk, environmental data are necessary because they have effects on the distribution of malaria vectors. But such data is often not easily accessible for those who are not familiar with remote sensing data (such as epidemiologists or public health practitioners).

    To assist public health practitioners, Wimberly et al., developed an application using GEE to download data needed for malaria risk prediction models [@wimberly2022]. The application allows the users to enter the date range of their interest and automatically download the environmental data without writing codes. Factors associated with malaria risk such as precipitation and land surface temperature as well as the indices sensitive to vegetation and moisture content such as NDVI, SAVI and EVI can be downloaded.

2.  I found a (rather dubious) study investigating urbanicity and brain behaviour using GEE[@xu2021]. The authors assessed urbanicity using 9 different measures obtained from GEE such as night-time light (NL), normalized difference built-up index (NDBI), normalized difference water index (NDWI), normalized difference vegetation index (NDVI) and five measures derived from land cover map. But it was not clear from the paper which sensors were selected for the indices.

# Reflection

I think for those who are able to write codes, GEE is great. However, those who are not, there is still a barrier to using GEE (as clear from the Wimberly paper [@wimberly2022], and thus by extension a barrier to using emote sensing data for researchers outside the discipline of remote sensing. Thankfully, I think I can consider myself as someone who can write codes after taking two python modules. So I am looking forward to exploring this more in the summer when I work on my dissertation.

## References
